export default {
  COLORS: {
    background: '#000000',
    neutral: '#C6C6C6',
    color: '#fff',
    primary: '#FFD12C',
    secondary: '#52DAD7',
    terciary: '#FFA652',
    quartenary: '#97D86C',
    colorTextSubmit: '#FFFFFF',
    colorTextSocialButton: '#7A7A7A',
    colorTextSingup: '#9e9999',
  },

  FONT_SIZE: {
    caption: 12,
    button: 14,
    bodySmall: 14,
    body: 16,
    large: 18,
    h6: 20,
    h5: 24,
    h4: 34,
    h3: 42,
    h2: 48,
    h1: 56,
  },
  FONTS: {
    LEXEND_BOLD: 'Lexend-Bold',
    LEXEND_LIGHT: 'Lexend-Light',
    LEXEND_REGULAR: 'Lexend-Regular',
    LEXEND_SEMI_BOLD: 'Lexend-SemiBold',
    NUNITO_BLACK: 'Nunito-Black',
  },
};
