export default {
  COLORS: {
    background: '#FFFFFF',
    neutral: '#C6C6C6',
    color: '#000',
    primary: '#FFBC01',
    secondary: '#00AEAC',
    terciary: '#FF8734',
    quartenary: '#84C55B',
    colorTextSubmit: '#FFFFFF',
    colorTextSocialButton: '#393939',
    colorTextSingup: '#4D4D4D',
    greyPrimary: '#F3F3F3',
    greySecondary: '#D9D9D9',
  },

  FONT_SIZE: {
    caption: 12,
    button: 14,
    bodySmall: 14,
    body: 16,
    large: 18,
    h6: 20,
    h5: 24,
    h4: 34,
    h3: 42,
    h2: 48,
    h1: 56,
  },
  FONTS: {
    LEXEND_BOLD: 'Lexend-Bold',
    LEXEND_LIGHT: 'Lexend-Light',
    LEXEND_REGULAR: 'Lexend-Regular',
    LEXEND_SEMI_BOLD: 'Lexend-SemiBold',
    NUNITO_BLACK: 'Nunito-Black',
  },
};
