declare module 'styled-components' {
    export interface DefaultTheme {
        COLORS: {
            background: string,
            whiteBackground: string,
            darkBackground: string,
            neutral: string,
            color: string,
            primary: string,
            secondary: string,
            terciary: string,
            quartenary: string,
            colorTextSubmit: string,
            colorTextSocialButton: string,
            colorTextSingup: string,
            greyPrimary: string,
            greySecondary: string,
        },
        FONT_SIZE: {
            caption: number,
            button: number,
            bodySmall: number,
            body: number,
            large: number,
            h6: number,
            h5: number,
            h4: number,
            h3: number,
            h2: number,
            h1: number,
        },
        FONTS: {
            LEXEND_BOLD: string,
            LEXEND_LIGHT: string,
            LEXEND_REGULAR: string,
            LEXEND_SEMI_BOLD: string,
            NUNITO_BLACK: string,
        },
    }
}